[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false

[programs.localnet]
staker = "8HVDihB8NrYpqzRNrFuiSPUC7B4rRqa8HFRJNWoxH4JK"

[programs.devnet]
staker = "8HVDihB8NrYpqzRNrFuiSPUC7B4rRqa8HFRJNWoxH4JK"

[registry]
url = "https://api.apr.dev"

[provider]
# Devnet for deployment
cluster = 'devnet'
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
